# coding: utf-8

import sys
from setuptools import setup, find_packages

NAME = "riseml"
VERSION = "0.3.10"


REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

REQUIRES += ['future', 'pyyaml', 'requests', 'flask', 'flask-cors', 'config_parser==0.1.0', 'jsonschema', 'websocket-client']

setup(
    name=NAME,
    version=VERSION,
    description="RiseML API client",
    author_email="contact@riseml.com",
    url="https://riseml.com",
    keywords=["RiseML"],
    entry_points={
        'console_scripts': [
            'riseml = riseml.__main__:main'
        ]
    },
    install_requires=REQUIRES,
    dependency_links=('git+ssh://git@github.com/riseml/config-parser.git@master#egg=config_parser-0.1.0', ),

    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
    """
)

