from .deploy import add_deploy_parser
from .execute import add_exec_parser
from .logs import add_logs_parser
from .train import add_train_parser
from .kill import add_kill_parser
from .system import add_system_parser
from .account import add_account_parser
from .status import add_status_parser
from .whoami import add_whoami_parser
from .init import add_init_parser
from .monitor import add_monitor_parser
from .user import add_user_parser