# coding: utf-8

"""
    RiseML API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.1.0
    Contact: contact@riseml.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat
from six import iteritems
import re


class Account(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, key=None, cluster_id=None, enabled_features=None):
        """
        Account - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'key': 'str',
            'cluster_id': 'str',
            'enabled_features': 'list[str]'
        }

        self.attribute_map = {
            'name': 'name',
            'key': 'key',
            'cluster_id': 'cluster_id',
            'enabled_features': 'enabled_features'
        }

        self._name = name
        self._key = key
        self._cluster_id = cluster_id
        self._enabled_features = enabled_features


    @property
    def name(self):
        """
        Gets the name of this Account.


        :return: The name of this Account.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Account.


        :param name: The name of this Account.
        :type: str
        """

        self._name = name

    @property
    def key(self):
        """
        Gets the key of this Account.


        :return: The key of this Account.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """
        Sets the key of this Account.


        :param key: The key of this Account.
        :type: str
        """

        self._key = key

    @property
    def cluster_id(self):
        """
        Gets the cluster_id of this Account.


        :return: The cluster_id of this Account.
        :rtype: str
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id):
        """
        Sets the cluster_id of this Account.


        :param cluster_id: The cluster_id of this Account.
        :type: str
        """

        self._cluster_id = cluster_id

    @property
    def enabled_features(self):
        """
        Gets the enabled_features of this Account.


        :return: The enabled_features of this Account.
        :rtype: list[str]
        """
        return self._enabled_features

    @enabled_features.setter
    def enabled_features(self, enabled_features):
        """
        Sets the enabled_features of this Account.


        :param enabled_features: The enabled_features of this Account.
        :type: list[str]
        """

        self._enabled_features = enabled_features

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
