# coding: utf-8

"""
    RiseML API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.1.0
    Contact: contact@riseml.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from pprint import pformat
from six import iteritems
import re


class Changeset(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, revision=None, message=None, created_at=None, config=None, repository=None):
        """
        Changeset - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'revision': 'str',
            'message': 'str',
            'created_at': 'int',
            'config': 'str',
            'repository': 'Repository'
        }

        self.attribute_map = {
            'id': 'id',
            'revision': 'revision',
            'message': 'message',
            'created_at': 'created_at',
            'config': 'config',
            'repository': 'repository'
        }

        self._id = id
        self._revision = revision
        self._message = message
        self._created_at = created_at
        self._config = config
        self._repository = repository


    @property
    def id(self):
        """
        Gets the id of this Changeset.


        :return: The id of this Changeset.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Changeset.


        :param id: The id of this Changeset.
        :type: str
        """

        self._id = id

    @property
    def revision(self):
        """
        Gets the revision of this Changeset.


        :return: The revision of this Changeset.
        :rtype: str
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """
        Sets the revision of this Changeset.


        :param revision: The revision of this Changeset.
        :type: str
        """

        self._revision = revision

    @property
    def message(self):
        """
        Gets the message of this Changeset.


        :return: The message of this Changeset.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this Changeset.


        :param message: The message of this Changeset.
        :type: str
        """

        self._message = message

    @property
    def created_at(self):
        """
        Gets the created_at of this Changeset.


        :return: The created_at of this Changeset.
        :rtype: int
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this Changeset.


        :param created_at: The created_at of this Changeset.
        :type: int
        """

        self._created_at = created_at

    @property
    def config(self):
        """
        Gets the config of this Changeset.


        :return: The config of this Changeset.
        :rtype: str
        """
        return self._config

    @config.setter
    def config(self, config):
        """
        Sets the config of this Changeset.


        :param config: The config of this Changeset.
        :type: str
        """

        self._config = config

    @property
    def repository(self):
        """
        Gets the repository of this Changeset.


        :return: The repository of this Changeset.
        :rtype: Repository
        """
        return self._repository

    @repository.setter
    def repository(self, repository):
        """
        Sets the repository of this Changeset.


        :param repository: The repository of this Changeset.
        :type: Repository
        """

        self._repository = repository

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
